{ config, pkgs, ntfyNotify, ... }:

let
  # Per-site values (deSEC subdomain + ACME email). Operator-managed,
  # outside the repo. Expected shape:
  #   { acmeDomain = "home.dedyn.io"; acmeEmail = "you@example.com"; }
  # For nixos-anywhere installs this file must exist ON THE WORKSTATION
  # running the install (flake eval happens there before the target
  # exists), not on the target. See hosts/main/README.md.
  site = import /etc/nixos/site.nix;

  # Shared options for every restic backup job on this host.
  # /etc/restic/env holds RESTIC_REPOSITORY= and RESTIC_PASSWORD=,
  # read by the service at runtime (expected repo:
  # sftp:restic@backupserver.<tailnet>.ts.net:/mnt/backups/homeserver).
  resticCommon = {
    environmentFile = "/etc/restic/env";
    initialize = true;
    timerConfig = {
      OnCalendar = "03:00";
      Persistent = true;
      RandomizedDelaySec = "30m";
    };
    pruneOpts = [
      "--keep-daily 7"
      "--keep-weekly 4"
      "--keep-monthly 6"
    ];
    checkOpts = [ ];   # empty = structural check every run, no --read-data
  };

  # mdadm invokes this on array events with argv: event, array, [device].
  # Routes to ntfy home-smart so RAID failures surface alongside SMART
  # alerts. Without a MAILADDR or PROGRAM, mdmon crashes at startup.
  # writeShellApplication (vs writeShellScript) adds `set -euo pipefail`
  # by default and runs shellcheck at build time.
  mdadmAlert = pkgs.writeShellApplication {
    name = "mdadm-alert";
    text = ''
      event="$1"
      array="''${2:-unknown}"
      device="''${3:-N/A}"
      ${ntfyNotify} home-smart 4 \
        "mdadm: $event on $array" \
        "Device: $device (host: homeserver)"
    '';
  };
in

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/alerts.nix
  ];

  # Operator alerts → local ntfy container (127.0.0.1:8085 via compose port map).
  alerts.ntfy.url = "http://127.0.0.1:8085";
  alerts.smartd.enable = true;
  alerts.tailscaleHealthcheck.enable = true;

  # ============================================================
  # TLS certificates via Let's Encrypt DNS-01 ACME through deSEC.
  # Produces a wildcard cert covering *.${site.acmeDomain} at
  # /var/lib/acme/${site.acmeDomain}/. Caddy reads it via a read-only
  # bind mount (see hosts/main/compose/caddy.yml + the `acme_tls`
  # snippet in Caddyfile).
  #
  # DNS provider credentials live in /etc/acme/credentials.env
  # (operator-managed, outside Nix, same pattern as /etc/restic/env and
  # /etc/ntfy/url). For deSEC the file contains `DESEC_TOKEN=...`; if you
  # ever switch providers, replace the variable name accordingly and
  # flip `dnsProvider` below.
  # ============================================================
  security.acme = {
    acceptTerms = true;
    defaults.email = site.acmeEmail;
  };
  security.acme.certs.${site.acmeDomain} = {
    domain = site.acmeDomain;
    extraDomainNames = [ "*.${site.acmeDomain}" ];
    dnsProvider = "desec";
    credentialsFile = "/etc/acme/credentials.env";
    group = "caddy-certs";
    reloadServices = [ "caddy-reload-certs.service" ];
  };

  # Group the acme user and the Caddy container both belong to, so
  # cert files (owned acme:caddy-certs, mode 0640) are readable by
  # Caddy. Fixed GID so compose's `group_add: ["2100"]` matches.
  users.groups.caddy-certs.gid = 2100;

  # Restart Caddy after each renewal so new cert files take effect.
  # `|| true` so renewal doesn't fail on first deploy before Caddy is up.
  systemd.services.caddy-reload-certs = {
    description = "Restart Caddy after ACME cert renewal";
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash -c '${pkgs.docker}/bin/docker restart caddy || true'";
    };
  };

  # ============================================================
  # Boot & Bootloader
  # ============================================================
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Cross-compile aarch64 (Pi backup host) from this x86_64 machine
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  # Enable mdadm in initrd/services so the RAID 10 array (declared in
  # ./disko.nix) assembles at boot. Per-partition kernel module list
  # is in ./hardware-configuration.nix; fileSystems and swapDevices
  # are generated by disko.
  boot.swraid.enable = true;

  # Route mdadm array-failure events to ntfy home-smart (see mdadmAlert
  # in the let block above). Without a MAILADDR or PROGRAM directive
  # mdmon.service crashes at startup.
  boot.swraid.mdadmConf = ''
    PROGRAM ${mdadmAlert}/bin/mdadm-alert
  '';

  # ============================================================
  # Networking
  # ============================================================
  networking.hostName = "homeserver";
  networking.networkmanager.enable = true;

  # ============================================================
  # Time & Locale
  # ============================================================
  time.timeZone = "Europe/Brussels";
  i18n.defaultLocale = "en_US.UTF-8";

  # ============================================================
  # Users
  # ============================================================
  users.users.stef = {
    isNormalUser = true;
    extraGroups = [ "wheel" "docker" ];
    # Set password on first boot with: passwd stef
  };

  # ============================================================
  # Nix CLI — enable flakes + nix-command for interactive use on the host
  # ============================================================
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # ============================================================
  # Docker
  # ============================================================
  virtualisation.docker = {
    enable = true;
    # Store Docker data on the RAID array, not the boot SSD
    daemon.settings = {
      data-root = "/mnt/data/docker";
    };
  };

  # ============================================================
  # SSH
  # ============================================================
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # ============================================================
  # Tailscale
  # ============================================================
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "server";
  };

  # ============================================================
  # Basic Packages
  # ============================================================
  environment.systemPackages = with pkgs; [
    git
    vim
    htop
    mdadm
    docker-compose
    curl
    wget
    restic
    pwgen       # needed to generate Seafile JWT_PRIVATE_KEY
  ];

  # ============================================================
  # Firewall
  # ============================================================
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [
      22      # SSH
      53      # DNS (AdGuard Home) — reachable on tailnet + LAN
      80      # HTTP  (Caddy)
      443     # HTTPS (Caddy)
    ];
    allowedUDPPorts = [
      53      # DNS (AdGuard Home)
      41641   # Tailscale direct connections
    ];
    # Trust all traffic from Tailscale interface
    trustedInterfaces = [ "tailscale0" ];
  };

  # ============================================================
  # DNS + ad-blocking (AdGuard Home)
  # Web UI bound to 127.0.0.1:3000, fronted by Caddy at
  # `adguard.${DOMAIN}`. DNS listens on 0.0.0.0:53; the firewall
  # above opens 53 for tailnet + LAN reach.
  #
  # mutableSettings = true: declarative config seeds the first run,
  # the AdGuard setup wizard creates the admin user, and the web UI
  # owns state thereafter. If you want to enforce declarative-only,
  # flip to false and declare users + filters explicitly.
  # ============================================================
  services.adguardhome = {
    enable = true;
    openFirewall = false;     # firewall above already opens 53
    mutableSettings = true;
    host = "127.0.0.1";
    port = 3000;
    settings = {
      dns = {
        bind_hosts = [ "0.0.0.0" ];
        port = 53;
        # Quad9 primary (adds malware-domain blocking), Cloudflare fallback.
        # Both over DoT so AdGuard → upstream traffic is encrypted.
        upstream_dns = [
          "tls://dns.quad9.net"
          "tls://1.1.1.1"
        ];
        # Plaintext resolvers used to bootstrap the DoT hostnames above.
        bootstrap_dns = [ "9.9.9.9" "1.1.1.1" ];
        # Reject DNS answers with invalid DNSSEC signatures (catches tampering).
        enable_dnssec = true;
      };
      filtering = {
        protection_enabled = true;
        filtering_enabled = true;
      };
      # Leave blocklists empty — pick them in the setup wizard on first run.
      filters = [ ];
    };
  };

  # ============================================================
  # Backups (restic → backupserver over SFTP/Tailscale)
  # Silent success ping + audible failure ping go to ntfy /home-backup.
  # ============================================================
  services.restic.backups = {
    docker-volumes = resticCommon // {
      paths = [ "/mnt/data/docker/volumes" ];
      exclude = [ "*.tmp" "*.log" ];
      extraBackupArgs = [ "--tag" "docker-volumes" ];
      backupCleanupCommand = "${ntfyNotify} home-backup 1 'Backup OK' 'docker-volumes snapshot completed'";
    };
    seafile-data = resticCommon // {
      paths = [ "/mnt/data/seafile" ];
      extraBackupArgs = [ "--tag" "seafile-data" ];
      backupCleanupCommand = "${ntfyNotify} home-backup 1 'Backup OK' 'seafile-data snapshot completed'";
    };
    # AdGuard Home's state (admin user, selected blocklists, custom rules)
    # lives outside /mnt/data because services.adguardhome uses DynamicUser
    # + StateDirectory. `/var/lib/AdGuardHome` is a symlink into
    # /var/lib/private/... ; restic follows the top-level symlink and
    # captures the underlying files. Caveat: on restore, the dynamic UID
    # of adguardhome may differ; a `systemctl stop adguardhome` +
    # `chown -R` to the current owning UID may be needed before restart.
    adguard-state = resticCommon // {
      paths = [ "/var/lib/AdGuardHome" ];
      extraBackupArgs = [ "--tag" "adguard-state" ];
      backupCleanupCommand = "${ntfyNotify} home-backup 1 'Backup OK' 'adguard-state snapshot completed'";
    };
  };

  # Wire each backup unit's failure path to the templated notifier from
  # modules/alerts.nix.
  systemd.services.restic-backups-docker-volumes.unitConfig.OnFailure =
    [ "ntfy-backup-failure@restic-backups-docker-volumes.service" ];
  systemd.services.restic-backups-seafile-data.unitConfig.OnFailure =
    [ "ntfy-backup-failure@restic-backups-seafile-data.service" ];
  systemd.services.restic-backups-adguard-state.unitConfig.OnFailure =
    [ "ntfy-backup-failure@restic-backups-adguard-state.service" ];

  # Monthly deep integrity check. `restic check` runs after every backup
  # and verifies structure/metadata; this timer additionally samples 10%
  # of pack data (`--read-data-subset=10%`) and decrypts+rehashes it,
  # catching bit-rot that the fast check can't. Over ~10 months the
  # whole repo gets verified statistically.
  #
  # Bandwidth note: 10% flows over SFTP/Tailscale from main to the Pi.
  # Fine on a LAN (Tailscale direct connect); if the Pi ever lives at a
  # site with a slow uplink, dial the percentage down or go quarterly.
  systemd.services.restic-check-deep = {
    description = "Deep restic repository check (--read-data-subset=10%)";
    path = [ pkgs.restic pkgs.openssh ];
    serviceConfig = {
      Type = "oneshot";
      EnvironmentFile = "/etc/restic/env";
      ExecStart = "${pkgs.restic}/bin/restic check --read-data-subset=10%";
      ExecStartPost = "${ntfyNotify} home-backup 1 'Backup check OK' 'Monthly deep restic check passed (10% subset)'";
      Nice = 19;
      IOSchedulingClass = "idle";
    };
    unitConfig.OnFailure = [ "ntfy-backup-failure@restic-check-deep.service" ];
  };
  systemd.timers.restic-check-deep = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "monthly";        # first of every month
      Persistent = true;
      RandomizedDelaySec = "6h";     # avoid pinning to 00:00 + don't collide with daily 03:00 backup
    };
  };

  # ============================================================
  # Automatic Upgrades
  # ============================================================
  system.autoUpgrade = {
    enable = true;
    allowReboot = false;
    dates = "04:30";
    flake = "/home/stef/server_config#main";
    flags = [ "-L" ];
  };

  # Only upgrade after both restic backup jobs succeeded today
  systemd.services.nixos-upgrade = {
    after = [
      "restic-backups-docker-volumes.service"
      "restic-backups-seafile-data.service"
    ];
    requires = [
      "restic-backups-docker-volumes.service"
      "restic-backups-seafile-data.service"
    ];
  };

  system.stateVersion = "25.11";
}
