{ config, lib, pkgs, operatorPubkeyPath, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/common.nix
  ];

  # Limine rather than systemd-boot: it can address partitions on other disks,
  # so a single menu lists both this install and the Arch install on the other
  # NVMe. Arch's UKI is chainloaded, which Limine deliberately exempts from its
  # own hash checks because firmware LoadImage verifies the signature against
  # the enrolled db key — so nothing here changes when Arch's kernel updates.
  #
  # secureBoot signs with the sbctl keys Arch already enrolled (/var/lib/sbctl).
  # autoGenerateKeys must stay false: minting a new PK/KEK/db would replace the
  # enrolled db and Arch would stop booting. See MIGRATION.md.
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.limine = {
    enable = true;
    maxGenerations = 10;
    secureBoot = {
      enable = true;
      autoGenerateKeys = false;
    };
    extraEntries = ''
      /Arch Linux
          protocol: chainload
          path: uuid(b57468df-5404-499b-b84e-5b8ea0108ce6):/EFI/Linux/arch-linux.efi

      /Arch Linux (fallback initramfs)
          protocol: chainload
          path: uuid(b57468df-5404-499b-b84e-5b8ea0108ce6):/EFI/Linux/arch-linux-fallback.efi
    '';
  };

  # Hibernate target is the btrfs swapfile declared in disko.nix. resume_offset
  # is deliberately absent — it can only be read off the real filesystem
  # (`btrfs inspect-internal map-swapfile -r /swap/swapfile`) and disko cannot
  # emit it. Without it resume silently no-ops rather than misbehaving.
  boot.resumeDevice = "/dev/mapper/cryptroot";

  networking.hostName = "workstation";
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Brussels";
  i18n.defaultLocale = "en_US.UTF-8";

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };

  users.users.stef = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" "audio" "input" "docker" ];
    shell = pkgs.zsh;
    openssh.authorizedKeys.keyFiles = [ operatorPubkeyPath ];
  };

  # uwsm starts Hyprland as a proper systemd user session, which is what
  # exports WAYLAND_DISPLAY / HYPRLAND_INSTANCE_SIGNATURE into the systemd
  # user environment — the waybar / hypridle / hyprpaper / hyprpolkitagent
  # user units all fail to start without it.
  programs.hyprland = {
    enable = true;
    withUWSM = true;
  };
  programs.uwsm.enable = true;
  programs.hyprlock.enable = true;   # also registers the hyprlock PAM service
  programs.zsh.enable = true;
  programs.thunar = {
    enable = true;
    plugins = with pkgs; [ thunar-archive-plugin thunar-volman ];
  };
  services.gvfs.enable = true;
  services.tumbler.enable = true;

  # Steam needs the module, not a bare package — it brings the FHS wrapper,
  # 32-bit graphics libs and controller udev rules. extraCompatPackages puts
  # GE-Proton on STEAM_EXTRA_COMPAT_TOOLS_PATHS, so it shows up in Steam's
  # compatibility dropdown declaratively instead of via protonup-qt.
  programs.steam = {
    enable = true;
    extraCompatPackages = [ pkgs.proton-ge-bin ];
  };
  programs.gamescope.enable = true;

  xdg.portal = {
    enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-hyprland
      pkgs.xdg-desktop-portal-gtk
    ];
  };

  # SDDM reads session .desktop files, so it picks up the hyprland-uwsm
  # session generated by programs.uwsm — no hand-written launch command.
  services.displayManager = {
    sddm = {
      enable = true;
      wayland.enable = true;
    };
    defaultSession = "hyprland-uwsm";
  };

  # polkit_gnome ships only an XDG autostart entry marked
  # OnlyShowIn=GNOME;XFCE, which never fires under Hyprland — so the agent
  # needs an explicit unit. uwsm reaches graphical-session.target only after
  # importing the session environment, so order against that.
  systemd.user.services."polkit-gnome-authentication-agent-1" = {
    description = "polkit-gnome-authentication-agent-1";
    after = [ "graphical-session.target" ];
    partOf = [ "graphical-session.target" ];
    wantedBy = [ "graphical-session.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
      Restart = "on-failure";
      RestartSec = 1;
      TimeoutStopSec = 10;
    };
  };

  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
    jack.enable = true;
  };

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # RADV (Vulkan) ships inside mesa on NixOS — unlike Arch there is no
  # separate vulkan-radeon package to add here.
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  services.fwupd.enable = true;
  services.fprintd.enable = true;
  services.ratbagd.enable = true;   # piper is its GUI

  services.printing = {
    enable = true;
    cups-pdf.enable = true;
  };
  services.avahi = {
    enable = true;
    nssmdns4 = true;                # .local name resolution via nsswitch
    openFirewall = true;
  };

  virtualisation.docker.enable = true;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  services.tailscale = {
    enable = true;
    useRoutingFeatures = "client";
    authKeyFile = "/etc/tailscale/authkey";
  };

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ ];
    allowedUDPPorts = [ 41641 ];
    trustedInterfaces = [ "tailscale0" ];
  };

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "claude-code"
      "spotify"
      "clion"
      "pycharm"
      "rider"
      "webstorm"
      # programs.steam installs both cfg.package and cfg.package.run.
      # proton-ge-bin and gamescope are free — no entry needed.
      "steam"
      "steam-unwrapped"
      "steam-run"
    ];

  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
  nix.optimise.automatic = true;

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" ];
  };

  # Baseline CLI tools come from modules/common.nix
  environment.systemPackages = with pkgs; [
    # Wayland desktop
    alacritty
    waybar
    wofi
    dunst
    hyprpaper
    hypridle           # no NixOS module for this one, unlike hyprlock
    brightnessctl
    pavucontrol
    grim
    slurp
    wl-clipboard
    cliphist
    playerctl
    wdisplays
    wev
    networkmanagerapplet
    polkit_gnome
    qt6.qtwayland

    # Shell + CLI
    stow
    file
    unzip
    jq
    ripgrep
    fd
    bat
    fzf
    fastfetch
    tmux
    zsh-autosuggestions      # sourced by the Stow-managed .zshrc
    zsh-syntax-highlighting
    zsh-completions
    zsh-fzf-tab

    # Development
    cmake
    docker-compose
    claude-code
    jetbrains.clion
    jetbrains.pycharm
    jetbrains.rider
    jetbrains.webstorm

    # System tools
    sbctl              # inspect/verify the Secure Boot chain: sbctl status|verify
    piper
    nvtopPackages.amd
    gparted
    qdirstat
    xarchiver

    # Apps
    # Bitwarden is used via the Firefox extension + the self-hosted Vaultwarden
    # web vault; the desktop app pulls an EOL Electron. See MIGRATION.md.
    firefox
    spotify
    gimp
    blender
    mpv
  ];

  programs.gnupg.agent = {
    enable = true;
    pinentryPackage = pkgs.pinentry-curses;
  };

  fonts.packages = with pkgs; [
    noto-fonts
    noto-fonts-color-emoji
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
  ];

  system.stateVersion = "26.05";
}
